### ISSUE TITLE
Feature Request: option to reverse the direction of truth table's rows

### ISSUE THREAD

**Issue by NudPiyapon** [Thumuss/truthfy#3]
It would be nice if there is an option to reverse the direction of truth table's rows.

For example, if `#truth-table($A and B$)` generates
| A | B | A and B |
|---|---|---------|
| 0 | 0 | 0       |
| 0 | 1 | 0       |
| 1 | 0 | 0       |
| 1 | 1 | 1       |

then `#truth-table($A and B$, reverse: true)` should generate
| A | B | A and B |
|---|---|---------|
| 1 | 1 | 1       |
| 1 | 0 | 0       |
| 0 | 1 | 0       |
| 0 | 0 | 0       |

**Comment by Thumuss** [comment]
Implemented in the last commit!

**Comment by Thumuss** [comment]
Pushed on typst universe
